config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  	root "todo_lists#index"
  		resources :todo_lists do
    	resources :todo_items do
    		member do
    			patch :complete
    		end
  		end
  	end
end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
  belongs_to :todo_list

  def completed?
  	!completed_at.blank?
  end
end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base
	belongs_to :user
	has_many :todo_items
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :todo_lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
	before_action :set_todo_list
	before_action :set_todo_item, except: [:create]

	def create
		@todo_item = @todo_list.todo_items.create(todo_item_params)
		redirect_to @todo_list
	end

	def destroy
		if @todo_item.destroy 
			flash[:success] = "Yehaw"
		else
			flash[:error] = "Nope, didn't work brah..."
		end
		redirect_to @todo_list
	end

	def complete
		@todo_item.update_attribute(:completed_at, Time.now)
		redirect_to @todo_list, notice: "Todo Item Completed!"
	end

	private

	def set_todo_list
		@todo_list = TodoList.find(params[:todo_list_id])
	end

	def set_todo_item
		@todo_item = TodoItem.find(params[:id])
	end

	def todo_item_params
		params[:todo_item].permit(:content)
	end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]
  before_action :correct_user, only: [:edit, :update, :destroy]


  def index
    if user_signed_in?
      @todo_lists = TodoList.where(user_id: current_user.id)
    else
      render :new_user
    end
  end

  def show
  end

  def new
    @todo_list = current_user.todo_lists.build
  end

  def edit
  end

  def create
    @todo_list = current_user.todo_lists.build(todo_list_params)

      if @todo_list.save
        redirect_to @todo_list, notice: 'Todo list was successfully created.'
      else
        render :new
      end
  end

  def update
    if @todo_list.update(todo_list_params)
      redirect_to @todo_list, notice: 'Todo list was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @todo_list.destroy
    redirect_to root_url, notice: 'Todo list was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    def correct_user
      @todo_list = current_user.todo_lists.find_by(id: params[:id])
      redirect_to todo_lists_path, notice: "Not Authorized" if @todo_list.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_list_params
      params.require(:todo_list).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lists Brah</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>
<!-- NOTICES -->
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<!-- BODY -->
<div class="container">
	<%= yield %>
</div>

<!-- FOOTER -->
<div class="footer">
<div class="footer-content">
  <% if user_signed_in? %>
    Logged in as <strong><%= current_user.email %></strong>.
    <%= link_to 'Edit Profile', edit_user_registration_path %> |
    <%= link_to "Logout", destroy_user_session_path, method: :delete %>
  <% end %>
</div>
</div>

</body>
</html>

app/views/todo_items/_form.html.erb
<%= form_for([@todo_list, @todo_list.todo_items.build]) do |f| %>
	<%= f.text_field :content, placeholder: "New Todo" %>
	<%= f.submit %>
<% end %>

app/views/todo_items/_todo_item.html.erb
<div class="row clearfix">
	<% if todo_item.completed? %>
		<div class="complete">
			<%= link_to complete_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch do %>
				<i style="opacity: 0.4;" class="fa fa-check"></i>
			<% end %>
		</div>
		<div class="todo_item">
			<p style="opacity: 0.4;"><strike><%= todo_item.content %></strike></p>
		</div>
		<div class="trash">
			<%= link_to todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: {confirm: "Are you sure you want to delete this?"} do %>
				<i class="fa fa-trash"></i>
			<% end %>
		</div>
	<!-- IF ITEM COMPLETE -->
	<% else %>
		<div class="complete">
			<%= link_to complete_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch do %>
				<i class="fa fa-check"></i>
			<% end %>
		</div>
		<div class="todo_item">
			<p><%= todo_item.content %></p>
		</div>
		<div class="trash">
			<%= link_to todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: {confirm: "Are you sure you want to delete this?"} do %>
				<i class="fa fa-trash"></i>
			<% end %>
		</div>
	<% end %>
</div>

app/views/todo_lists/_form.html.erb
<%= form_for(@todo_list) do |f| %>
  <% if @todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
      <% @todo_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todo_lists/edit.html.erb
<h1 class="todo_list_title">Edit Todo List</h1>

<div class="forms">
	<%= render 'form' %>
</div>

<div class="links">
	<%= link_to 'Show', @todo_list %> |
	<%= link_to 'Cancel', todo_lists_path %>
</div>

app/views/todo_lists/index.html.erb
<div class="col-md-12">
	<div class="panel panel-default main">
		<div class="panel-body">

			<% @todo_lists.each do |todo_list| %>
			  <div class="index_row clearfix">
			    <h2 class="todo_list_title"><%= link_to todo_list.title, todo_list %></h2>
			    <p class="todo_list_sub_title"><%= todo_list.description %> </p>
			  </div>
			<% end %>

			<div class="links">
			  <%= link_to "Create New List", new_todo_list_path %>
			</div>
		</div>
	</div>
</div>

app/views/todo_lists/new.html.erb
<h1 class="todo_list_title">New Todo List</h1>

<div class="forms">
	<%= render 'form' %>
</div>

<div class="links">
	<%= link_to 'Back', todo_lists_path %>
</div>

app/views/todo_lists/new_user.erb
<div class="col-md-12">
	<div class="panel panel-default main">
		<div class="panel-body">
			<h2 class="todo_list_title">Create a list brah!</h2>
			<br />
			<p class="todo_list_sub_title">Hey Brah, time to create some lists. <br />Create an account or sign in.</p>
			<div class="links">
			  <%= link_to "Create Account", new_user_registration_path %> |
			  <%= link_to "Login", new_user_session_path %>
			</div>
		</div>
	</div>
</div>

app/views/todo_lists/show.html.erb
<div class="col-md-12">
	<div class="panel panel-default">
		<div class="panel-body">
			<h2 class="todo_list_title"><%= @todo_list.title %></h2>
			<p class="todo_list_sub_title"><%= @todo_list.description %></p>
			
			<div id="todo_items_wrapper">
				<%= render @todo_list.todo_items %>
				<div id="form">
					<%= render "todo_items/form" %>
				</div>
			</div>

			<div class="links">
				<%= link_to 'Edit Details', edit_todo_list_path(@todo_list) %> |
				<%= link_to 'View All Lists', todo_lists_path %> | 
				<%= link_to 'Delete', todo_list_path(@todo_list), method: :delete, data: {confirm: "Are you sure?"} %>
			</div>
		</div>
	</div>
</div>